version: "3.8"

services:
  backend:
    build: .
    container_name: docxtract-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/app
      
 frontend:
    build:
      context: ../frontend
    container_name: docxtract-frontend
    ports:
      - "3000:80"

  mongo:
    image: mongo:6
    container_name: docxtract-mongo
    restart: always
    ports:
      - "27017:27017"
